apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: kub.techlabnews-com-cert
  namespace: traefik 
spec:
  secretName: kub.techlabnews-com-cert-secret
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: '*.kub.techlabnews.com'
  subject:
   organizations:
     - kub.techlabnews 
  dnsNames:
    - kub.techlabnews.com 
    - '*.kub.techlabnews.com'
  issuerRef:
    name: kub.techlabnews-ca-issuer 
    kind: ClusterIssuer
